files = [
    '../servicedesk/plugin/src/main/resources/servicedesk/customer/feature/helpcenterbranding/help-center-branding.soy',
    '../servicedesk/plugin/src/main/resources/servicedesk/internal/feature/sla-panel/sd-sla-view.soy',
    '../servicedesk/plugin/src/main/resources/servicedesk/notifications/conversational/custom-email-notifications.soy',
    '../servicedesk/plugin/src/main/resources/servicedesk/shared/components/precondition/view/alert.soy',
    '../servicedesk/plugin/src/main/resources/servicedesk/shared/utils/utils.soy',
    '../servicedesk/project-ui/src/main/resources/servicedesk/internal/project/feature/queue-table/queue-table.soy',
    '../servicedesk/project-ui/src/main/resources/servicedesk/internal/project/feature/sla-goals/sla-goals.soy',
    '../servicedesk/project-ui/src/main/resources/servicedesk/internal/project/pages/custom-queue/custom-queue.soy',
    '../servicedesk/project-ui/src/main/resources/servicedesk/internal/project/pages/customers/invite-customers/invite-customers-view.soy',
    '../servicedesk/project-ui/src/main/resources/servicedesk/internal/project/pages/incoming-email/addemailaccountdialog/add-email-account-dialog.soy',
    '../servicedesk/project-ui/src/main/resources/servicedesk/internal/project/pages/kb-settings/confluence-knowledge-base.soy',
    '../servicedesk/project-ui/src/main/resources/servicedesk/internal/project/pages/organisation/organisation-page.soy',
    '../servicedesk/project-ui/src/main/resources/servicedesk/internal/project/pages/request-type-edit/edit-request-type.soy',
    '../servicedesk/project-ui/src/main/resources/servicedesk/internal/project/pages/sla/import/import-sla-module.soy',
    '../servicedesk/project-ui/src/main/resources/servicedesk/internal/project/pages/sla/sla.soy',
    '../servicedesk/sd-components/approvals/approvals-plugin/src/main/resources/servicedesk/internal/approvals/feature/approval-configuration/approval-configuration.soy',
    '../servicedesk/sd-components/approvals/approvals-plugin/src/main/resources/servicedesk/internal/approvals/feature/create-approval/create-approval.soy',
    '../servicedesk/sd-components/automation-modules/automation-modules-plugin/src/main/resources/servicedesk/internal/agent/settings/automation/modules/actions/servicedesk-comment/servicedesk-comment-then-action.soy',
    '../servicedesk/sd-components/canned-responses/canned-responses-plugin/src/main/resources/servicedesk/internal/cannedresponses/canned-responses.soy',
    '../servicedesk/sd-components/core-ui/src/main/resources/servicedesk/internal-api/core/feature/select-dropdown/select-dropdown.soy',
    '../servicedesk/sd-components/core-ui/src/main/resources/servicedesk/vendor/aui-templates/avatar.soy',
    '../servicedesk/sd-components/core-ui/src/main/resources/servicedesk/vendor/aui-templates/badges.soy',
    '../servicedesk/sd-components/core-ui/src/main/resources/servicedesk/vendor/aui-templates/buttons.soy',
    '../servicedesk/sd-components/core-ui/src/main/resources/servicedesk/vendor/aui-templates/dialog2.soy',
    '../servicedesk/sd-components/core-ui/src/main/resources/servicedesk/vendor/aui-templates/dropdown2.soy',
    '../servicedesk/sd-components/core-ui/src/main/resources/servicedesk/vendor/aui-templates/form.soy',
    '../servicedesk/sd-components/core-ui/src/main/resources/servicedesk/vendor/aui-templates/group.soy',
    '../servicedesk/sd-components/core-ui/src/main/resources/servicedesk/vendor/aui-templates/icons.soy',
    '../servicedesk/sd-components/core-ui/src/main/resources/servicedesk/vendor/aui-templates/labels.soy',
    '../servicedesk/sd-components/core-ui/src/main/resources/servicedesk/vendor/aui-templates/lozenges.soy',
    '../servicedesk/sd-components/core-ui/src/main/resources/servicedesk/vendor/aui-templates/message.soy',
    '../servicedesk/sd-components/core-ui/src/main/resources/servicedesk/vendor/aui-templates/page.soy',
]

puts files.select { |f| `node index.js #{f} &>/dev/null`; $?.exitstatus != 0 }.join("\n")
